# Generated by Django 5.1.6 on 2025-02-20 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_name', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=100)),
                ('cities', models.TextField(help_text="Enter city names separated by ',")),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('accommodation_name', models.CharField(blank=True, max_length=255, null=True)),
                ('accommodation_type', models.CharField(choices=[('Hotel', 'Hotel'), ('Airbnb', 'Airbnb'), ('Hostel', 'Hostel'), ('Other', 'Other')], default='Hotel', max_length=50)),
                ('transport_name', models.CharField(blank=True, max_length=255, null=True)),
                ('transport_type', models.CharField(choices=[('Flight', 'Flight'), ('Train', 'Train'), ('Bus', 'Bus'), ('Car/Taxi', 'Car,Taxi')], default='Flight', max_length=50)),
                ('itinerary', models.TextField(blank=True, help_text='Enter itinerary details for each day.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
