# Generated by Django 5.1.6 on 2025-02-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='transport_mode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
