# Generated by Django 5.1.6 on 2025-02-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_transport_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='transport_mode',
            field=models.CharField(choices=[('Flight', 'Flight'), ('Train', 'Train'), ('Bus', 'Bus'), ('Car/Taxi', 'Car,Taxi')], default='Flight', max_length=50),
        ),
    ]
