# Generated by Django 5.1.6 on 2025-03-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_activitysuggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triplocation',
            name='cities',
            field=models.TextField(blank=True),
        ),
    ]
