# Generated by Django 5.1.6 on 2025-03-03 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_trip_transport_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='accommodation_name',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='accommodation_type',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='country',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='itinerary',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='transport_mode',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='trip_name',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='trip',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='TripBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='trips.trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accommodation_type', models.CharField(choices=[('hotel', 'Hotel'), ('hostel', 'Hostel'), ('airbnb', 'Airbnb'), ('camping', 'Camping'), ('other', 'Other')], max_length=100)),
                ('transport_type', models.CharField(choices=[('car', 'Car'), ('plane', 'Plane'), ('train', 'Train'), ('bus', 'Bus'), ('walking', 'Walking'), ('other', 'Other')], max_length=100)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='trips.trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('cities', models.TextField(help_text="separate cities with ',")),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='trips.trip')),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('morning', models.TextField(blank=True, null=True)),
                ('afternoon', models.TextField(blank=True, null=True)),
                ('evening', models.TextField(blank=True, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_days', to='trips.trip')),
            ],
            options={
                'ordering': ['day_number'],
                'unique_together': {('trip', 'day_number')},
            },
        ),
    ]
