# Generated by Django 5.1.6 on 2025-03-03 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_remove_trip_accommodation_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tripdetails',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='tripbudget',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='triplocation',
            name='trip',
        ),
        migrations.DeleteModel(
            name='ItineraryDay',
        ),
        migrations.DeleteModel(
            name='TripDetails',
        ),
        migrations.DeleteModel(
            name='TripBudget',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
        migrations.DeleteModel(
            name='TripLocation',
        ),
    ]
