# Generated by Django 5.1.6 on 2025-03-03 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='name',
            new_name='trip_name',
        ),
    ]
